### PR TITLE
fix crashes on prev_boundary

### LINKED ISSUE #38: Sometimes GraphemeCursor::prev_boundary returns PrevChunk but can't process anymore
I got a sample code:
```rust
let s = "abcd";
let mut cursor = GraphemeCursor::new(3, s.len(), false);
assert_eq!(cursor.prev_boundary(&s[2..], 2), Err(GraphemeIncomplete::PrevChunk));
assert_eq!(cursor.prev_boundary(&s[..2], 0), Ok(Some(2)));
```

On the second assertion, it instead returns `Err(GraphemeIncomplete::InvalidOffset)`. If it starts from position 4, as is written in the doc comment, it works. However it does not work when the cursor position starts from 3.

### PR DESCRIPTION
**Pull request by jmuk**
Fixes #38, #39

### CODE REVIEW

File: src/grapheme.rs [hunk 1]
```diff
@@ -665,7 +669,6 @@ impl GraphemeCursor {
     }
 }
 
-#[test]
```
Comment (raphlinus) [inline src/grapheme.rs]: This seems wrong to me.
